export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    INTRO_SCENE: 'INTRO_SCENE',
    BATTLE_SCENE: 'BATTLE_SCENE',
    OUTRO_SCENE: 'OUTRO_SCENE',
    CREDITS_SCENE: 'CREDITS_SCENE'
})