export const BATTLE_BACKGROUND_ASSET_KEYS = Object.freeze({
  CAVE: 'CAVE',
});

export const FIGHTER_ASSET_KEYS = Object.freeze({
  PLAYER: 'PLAYER',
  ENEMY: 'ENEMY',
});

export const BATTLE_ASSET_KEYS = Object.freeze({
  HEALTH_BAR_BACKGROUND: 'HEALTH_BAR_BACKGROUND',
});

export const UI_ASSET_KEYS = Object.freeze({
  CURSOR: 'CURSOR',
  SCROLL_UP: 'SCROLL_UP',
  SCROLL_DOWN: 'SCROLL_DOWN',
  SCROLL_BAR: 'SCROLL_BAR',
  TEXT_WINDOW: 'TEXT_WINDOW',
  TEXT_DIALOGUE_WINDOW: 'TEXT_DIALOGUE_WINDOW',
  BATTLE_PORTRAITS: 'BATTLE_PORTRAITS',
  NINESLICE: 'NINESLICE',
  TEXT_DIALOGUE: 'TEXT_DIALOGUE',
  TEXT_WINDOW_TOP: 'TEXT_WINDOW_TOP',
  TEXT_WINDOW_MIDDLE: 'TEXT_WINDOW_MIDDLE',
  TEXT_WINDOW_BOTTOM: 'TEXT_WINDOW_BOTTOM',
});

export const DATA_ASSET_KEYS = Object.freeze({
  PLAYER_ATTACKS: 'PLAYER_ATTACKS',
  ENEMY_ATTACKS: 'ENEMY_ATTACKS',
});

export const MUSIC_KEYS = Object.freeze({
  BATTLE_MUSIC: 'BATTLE_MUSIC',
  INTRO_MUSIC: 'INTRO_MUSIC',
  OUTRO_MUSIC: 'OUTRO_MUSIC',
  CREDITS_MUSIC: 'CREDITS_MUSIC',
});